**Matrices:**  
A = [[1, 2, 0], [0, 1, 1], [3, 0, 2]]  
B = [[2, 1, 1], [1, 0, 3], [0, 2, 1]]  

1. Calcula A × B y la traspuesta de B.  
2. Calcula el determinante de A y, si existe, su inversa.

In [11]:
import numpy as np

A = np.array([[1, 2, 0], [0, 1, 1], [3, 0, 2]]) 
B = np.array([[2, 1, 1], [1, 0, 3], [0, 2, 1]]) 

C = np.dot(A, B)
determinante = np.linalg.det(A)
print("*"*55)
print(f"El producoto de las matrices A y B es:  \n {C}")
print("*"*55)

print(f"El determinante de la matriz A es: {determinante}")
print("*"*55)

if determinante == 0:
    print("La matriz no tiene matriz inversa.")
else:
    inversa = np.linalg.inv(A)
    print(f"La matriz inversa de A es \n: {inversa}")







*******************************************************
El producoto de las matrices A y B es:  
 [[4 1 7]
 [1 2 4]
 [6 7 5]]
*******************************************************
El determinante de la matriz A es: 7.999999999999998
*******************************************************
La matriz inversa de A es 
: [[ 0.25  -0.5    0.25 ]
 [ 0.375  0.25  -0.125]
 [-0.375  0.75   0.125]]


**Vectores:**  
<!-- u = [1, -2, 3]   -->
v = [0, 1, 4]  

1. Calcula el producto interno u·v.  
2. Calcula la magnitud y el ángulo entre los vectores.

In [15]:
u = np.array([1, -2, 3])
v = np.array([0, 1, 4])

producto = np.dot(u, v)

magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)

cos_theta = producto / (magnitud_u * magnitud_v)
angulo_rad = np.arccos(cos_theta)
angulo_deg = np.degrees(angulo_rad)

print(f"El vector {u}, tiene una magnitud de {magnitud_u}")
print(f"El vector {v}, tiene una magnitud de {magnitud_v}")
print(f"El producto entre los dos vectores es de: {producto}")
print(f"El angulo entre los dos vectores es de: {angulo_deg}")

El vector [ 1 -2  3], tiene una magnitud de 3.7416573867739413
El vector [0 1 4], tiene una magnitud de 4.123105625617661
El producto entre los dos vectores es de: 10
El angulo entre los dos vectores es de: 49.59369316056338


**Derivadas:**  
f(x) = x**4 - 3*x**3 + 2*x - 5  

1. Calcula f'(x) y f''(x).  
2. Evalúa en x = 2 y comenta la concavidad.
"""

In [27]:
import sympy as sp 

x = sp.Symbol("x")

f = x**4 - 3*x**3 + 2*x -5

df_dx = sp.diff(f, x)
d2f_d2x = sp.diff(f, x,2)

f_subs = f.subs(x, 2)
f2_subs = d2f_d2x.subs(x, 2)


print(f"La derivada de la función {f} es: {df_dx}.")
print(f"La derivada de la función {f} es: {d2f_d2x}.")

if f2_subs > 0:
    print("Cóncava hacia arriba (mínimo local o convexa).")
elif f2_subs < 0:
    print("Cóncava hacia abajo (máximo local o cóncava).")
else:
    print("Punto de inflexión.")


La derivada de la función x**4 - 3*x**3 + 2*x - 5 es: 4*x**3 - 9*x**2 + 2.
La derivada de la función x**4 - 3*x**3 + 2*x - 5 es: 6*x*(2*x - 3).
Cóncava hacia arriba (mínimo local o convexa).
