"""
# Práctica de Python – Ejercicios Combinados

📌 Instrucciones generales:

1. Cada estudiante debe elegir **uno** de los siguientes cinco ejercicios para resolver.  
2. No más de **11 estudiantes por ejercicio**.  
3. Deben escribir su **nombre completo** en la sección indicada debajo del ejercicio elegido.  
4. Todos los ejercicios se resuelven usando Python (NumPy y SymPy).  
5. Cada ejercicio incluye:
   - Operaciones con matrices
   - Operaciones con vectores
   - Derivadas (normales, parciales, de funciones compuestas o sigmoide)
"""

# ----------------------------------------------------------
# EJERCICIO 5
# ----------------------------------------------------------
"""
## Ejercicio 5

**Matrices:**  
A = [[1, 1], [2, 3]]  
B = [[0, 2], [1, 1]]  

1. Calcula A + B, A - B y A × B.  
2. Calcula la traspuesta de A y la inversa de B (si existe).

**Vectores:**  
u = [2, 3]  
v = [1, -1]  

1. Calcula el producto interno u·v y determina ortogonalidad.  
2. Calcula magnitudes y ángulo entre u y v.

**Derivadas:**  
σ(x) = 1 / (1 + exp(-x))  # Función sigmoide  

1. Calcula σ'(x) simbólicamente y simplifícala.  
2. Evalúa σ'(0) y σ'(1) y explica su interpretación.
"""

# Nombre del estudiante:
# Nombre:
Vladimir Espinoza
Alan Palma
Fernando Quezada
Krister Figueroa
William Vera
Alejandro Obando
John Vera
Aisha Gómez
Wladimir Paredes

In [ ]:
!pip install sympy
import numpy as np
import sympy as sp
print("Matrices")
A = np.array([[1, 1],
              [2, 3]])

B = np.array([[0, 2],
              [1, 1]])

print(f"Matriz A:\n{A}")
print(f"Matriz B:\n{B}\n")

suma_AB = A + B
print(f"Suma A + B:\n{suma_AB}\n")

resta_AB = A - B
print(f"Resta A - B:\n{resta_AB}\n")

producto_AB = A @ B  
print(f"Producto A x B:\n{producto_AB}\n")

traspuesta_A = A.T 
print(f"Traspuesta de A (A^T):\n{traspuesta_A}\n")

try:
    inversa_B = np.linalg.inv(B)
    print(f"Inversa de B (B^-1):\n{inversa_B}\n")
except np.linalg.LinAlgError:
    print("La matriz B no tiene inversa (es singular).\n")


print("Vectores")

u = np.array([2, 3])
v = np.array([1, -1])

print(f"Vector u: {u}")
print(f"Vector v: {v}\n")

producto_interno_uv = np.dot(u, v)
print(f"Producto interno u·v: {producto_interno_uv}")

if producto_interno_uv == 0:
    print("Los vectores u y v SON ortogonales.\n")
else:
    print("Los vectores u y v NO SON ortogonales.\n")

magnitud_u = np.linalg.norm(u)
magnitud_v = np.linalg.norm(v)
print(f"Magnitud de u (||u||): {magnitud_u}")
print(f"Magnitud de v (||v||): {magnitud_v}\n")

cos_theta = producto_interno_uv / (magnitud_u * magnitud_v)
cos_theta = np.clip(cos_theta, -1, 1)

angulo_rad = np.arccos(cos_theta)
angulo_grados = np.degrees(angulo_rad)

print(f"Ángulo entre u y v (radianes): {angulo_rad}")
print(f"Ángulo entre u y v (grados): {angulo_grados:.2f}°\n")


print("Cálculo de Derivadas (Función Sigmoide)")

x = sp.symbols('x')

sigma = 1 / (1 + sp.exp(-x))
print(f"Función σ(x) = {sigma}\n")

sigma_prima = sp.diff(sigma, x)
print(f"Derivada σ'(x) (sin simplificar) = {sigma_prima}\n")

sigma_prima_simplificada = sigma * (1 - sigma)
sigma_prima_simplificada_sympy = sp.simplify(sigma_prima)

print(f"Derivada σ'(x) (simplificada por SymPy) = {sigma_prima_simplificada_sympy}\n")
print(f"Forma alternativa σ(x)(1-σ(x)) = {sp.simplify(sigma_prima_simplificada)}\n")

valor_sigma_prima_0 = sigma_prima_simplificada_sympy.subs(x, 0)
print(f"σ'(0) = {valor_sigma_prima_0}")
print(f"Valor numérico de σ'(0) = {valor_sigma_prima_0.evalf()}\n")


valor_sigma_prima_1 = sigma_prima_simplificada_sympy.subs(x, 1)
print(f"σ'(1) = {valor_sigma_prima_1}")
print(f"Valor numérico de σ'(1) ≈ {valor_sigma_prima_1.evalf()}\n")

print(f"La derivada de la función sigmoide, σ'(x), representa la 'tasa de cambio' o la 'pendiente' de la curva sigmoide en el punto x.")
print(f" - σ'(0) = {valor_sigma_prima_0.evalf()}: Este es el punto de máxima pendiente. La función sigmoide cambia más rápidamente en x=0.")
print(f" - σ'(1) ≈ {valor_sigma_prima_1.evalf()}: En x=1, la pendiente ha disminuido. A medida que |x| (el valor absoluto de x) aumenta, la pendiente se acerca a 0 (la curva se aplana).")
print("En redes neuronales, esta derivada es crucial para el 'backpropagation', ya que indica cuánto debe ajustarse un peso. Una derivada cercana a 0 (como ocurre lejos del centro) puede llevar al problema del 'gradiente evanescente' (vanishing gradient).")

Matrices
Matriz A:
[[1 1]
 [2 3]]
Matriz B:
[[0 2]
 [1 1]]

Suma A + B:
[[1 3]
 [3 4]]

Resta A - B:
[[ 1 -1]
 [ 1  2]]

Producto A x B:
[[1 3]
 [3 7]]

Traspuesta de A (A^T):
[[1 2]
 [1 3]]

Inversa de B (B^-1):
[[-0.5  1. ]
 [ 0.5  0. ]]

Vectores
Vector u: [2 3]
Vector v: [ 1 -1]

Producto interno u·v: -1
Los vectores u y v NO SON ortogonales.

Magnitud de u (||u||): 3.605551275463989
Magnitud de v (||v||): 1.4142135623730951

Ángulo entre u y v (radianes): 1.7681918866447774
Ángulo entre u y v (grados): 101.31°

Cálculo de Derivadas (Función Sigmoide)
Función σ(x) = 1/(1 + exp(-x))

Derivada σ'(x) (sin simplificar) = exp(-x)/(1 + exp(-x))**2

Derivada σ'(x) (simplificada por SymPy) = 1/(4*cosh(x/2)**2)

Forma alternativa σ(x)(1-σ(x)) = 1/(4*cosh(x/2)**2)

σ'(0) = 1/4
Valor numérico de σ'(0) = 0.250000000000000

σ'(1) = 1/(4*cosh(1/2)**2)
Valor numérico de σ'(1) ≈ 0.196611933241482

--- Interpretación de la Derivada Sigmoide ---
La derivada de la función sigmoide, σ'(x), representa 